export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Mainpage } from './Mainpage'
// export { default as Wishlist } from './Wishlist'
export { default as History } from './History'
export { default as DetailTickets } from './DetailTickets'
export { default as DetailEvent } from './DetailEvent'